// ============================================================
//  AUTO-GENERATED by scripts/gen-data.mjs — do not edit by hand.
//  Re-run `node scripts/gen-data.mjs` after changing /public.
// ============================================================

export type Product = {
  id: string;
  name: string;
  description: string;
  quality: string;
  image: string;
};

export type ProductGroup = {
  id: string;
  label: string;
  items: Product[];
};

export type Category = {
  slug: string;
  name: string;
  icon: string;
  gradient: string;
  cover: string;
  tagline: string;
  description: string;
  groups: ProductGroup[];
  count: number;
};

export const CATEGORIES: Category[] = [
  {
    "slug": "american-football",
    "name": "American Football",
    "icon": "Shield",
    "gradient": "from-amber-500/25 to-brand/5",
    "cover": "/SPORTS CETAGORY/AMERICAN FOOTBALL.png",
    "tagline": "Custom american football uniforms, jerseys & team wear",
    "description": "Fully customizable American Football uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "american-football-uniforms-alternate-football-uniforms",
            "name": "Alternate Football Uniforms",
            "quality": "Pro Kit",
            "image": "/american football uniform/products/alternate-football-uniforms.webp",
            "description": "Custom-sublimated alternate football uniforms, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-uniforms-professional-away-football-uniforms",
            "name": "Professional Away Football Uniforms",
            "quality": "Pro Kit",
            "image": "/american football uniform/products/professional-away-football-uniforms.webp",
            "description": "Custom-sublimated professional away football uniforms, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-uniforms-professional-football-uniforms",
            "name": "Professional Football Uniforms",
            "quality": "Pro Kit",
            "image": "/american football uniform/products/professional-football-uniforms.webp",
            "description": "Custom-sublimated professional football uniforms, made to order for american football teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "american-football-jerseys-compression-shirt",
            "name": "Compression Shirt",
            "quality": "Custom Fit",
            "image": "/american football uniform/shirts/compression-shirt.webp",
            "description": "Custom-sublimated compression shirt, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-jerseys-football-fan-jerseys",
            "name": "Football Fan Jerseys",
            "quality": "Custom Fit",
            "image": "/american football uniform/shirts/football-fan-jerseys.webp",
            "description": "Custom-sublimated football fan jerseys, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-jerseys-football-practice-jerseys",
            "name": "Football Practice Jerseys",
            "quality": "Custom Fit",
            "image": "/american football uniform/shirts/football-practice-jerseys 3.webp",
            "description": "Custom-sublimated football practice jerseys, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-jerseys-long-sleeve-t-shirt",
            "name": "Long Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/american football uniform/shirts/long-sleeve-t-shirt.webp",
            "description": "Custom-sublimated long sleeve t shirt, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-jerseys-short-sleeve-t-shirt",
            "name": "Short Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/american football uniform/shirts/short-sleeve-t-shirt.webp",
            "description": "Custom-sublimated short sleeve t shirt, made to order for american football teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "american-football-bottoms-compression-shorts",
            "name": "Compression Shorts",
            "quality": "Performance",
            "image": "/american football uniform/shorts&pent/compression-shorts.webp",
            "description": "Custom-sublimated compression shorts, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-bottoms-sweatpant",
            "name": "Sweatpant",
            "quality": "Performance",
            "image": "/american football uniform/shorts&pent/sweatpant.webp",
            "description": "Custom-sublimated sweatpant, made to order for american football teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "american-football-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/american football uniform/hodies/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/american football uniform/hodies/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-outerwear-quarter-zipper-pullover",
            "name": "Quarter Zipper Pullover",
            "quality": "Team Wear",
            "image": "/american football uniform/hodies/quarter-zipper-pullover.webp",
            "description": "Custom-sublimated quarter zipper pullover, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-outerwear-varsity-jacket",
            "name": "Varsity Jacket",
            "quality": "Team Wear",
            "image": "/american football uniform/hodies/varsity-jacket.webp",
            "description": "Custom-sublimated varsity jacket, made to order for american football teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "american-football-accessories-cape",
            "name": "Cape",
            "quality": "Team Gear",
            "image": "/american football uniform/accessries/cape.webp",
            "description": "Custom-sublimated cape, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-accessories-duffle-bag",
            "name": "Duffle Bag",
            "quality": "Team Gear",
            "image": "/american football uniform/accessries/duffle-bag.webp",
            "description": "Custom-sublimated duffle bag, made to order for american football teams in your colors with logo, names & numbers."
          },
          {
            "id": "american-football-accessories-skull-cap",
            "name": "Skull Cap",
            "quality": "Team Gear",
            "image": "/american football uniform/accessries/skull-cap.webp",
            "description": "Custom-sublimated skull cap, made to order for american football teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 17
  },
  {
    "slug": "basketball",
    "name": "Basketball",
    "icon": "Dribbble",
    "gradient": "from-orange-500/25 to-brand/5",
    "cover": "/SPORTS CETAGORY/BASKETBALL.png",
    "tagline": "Custom basketball uniforms, jerseys & team wear",
    "description": "Fully customizable Basketball uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "basketball-uniforms-round-neck-basketball-uniforms",
            "name": "Round Neck Basketball Uniforms",
            "quality": "Pro Kit",
            "image": "/basketball uniform/products/round-neck-basketball-uniforms.webp",
            "description": "Custom-sublimated round neck basketball uniforms, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-uniforms-round-neck-reversible-uniforms",
            "name": "Round Neck Reversible Uniforms",
            "quality": "Pro Kit",
            "image": "/basketball uniform/products/round-neck-reversible-uniforms.webp",
            "description": "Custom-sublimated round neck reversible uniforms, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-uniforms-v-neck-basketball-uniforms",
            "name": "V Neck Basketball Uniforms",
            "quality": "Pro Kit",
            "image": "/basketball uniform/products/v-neck-basketball-uniforms.webp",
            "description": "Custom-sublimated v neck basketball uniforms, made to order for basketball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "basketball-jerseys-long-sleeve-shooting-shirt",
            "name": "Long Sleeve Shooting Shirt",
            "quality": "Custom Fit",
            "image": "/basketball uniform/shirts/long-sleeve-shooting-shirt.webp",
            "description": "Custom-sublimated long sleeve shooting shirt, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-jerseys-performance-polo",
            "name": "Performance Polo",
            "quality": "Custom Fit",
            "image": "/basketball uniform/shirts/performance-polo.webp",
            "description": "Custom-sublimated performance polo, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-jerseys-quarter-zipper-jersey",
            "name": "Quarter Zipper Jersey",
            "quality": "Custom Fit",
            "image": "/basketball uniform/shirts/quarter-zipper-jersey.webp",
            "description": "Custom-sublimated quarter zipper jersey, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-jerseys-short-sleeve-t-shirt",
            "name": "Short Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/basketball uniform/shirts/short-sleeve-t-shirt.webp",
            "description": "Custom-sublimated short sleeve t shirt, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-jerseys-sleeveless-t-shirts",
            "name": "Sleeveless T Shirts",
            "quality": "Custom Fit",
            "image": "/basketball uniform/shirts/sleeveless-t-shirts.webp",
            "description": "Custom-sublimated sleeveless t shirts, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-jerseys-v-neck-reversible-jerseys",
            "name": "V Neck Reversible Jerseys",
            "quality": "Custom Fit",
            "image": "/basketball uniform/shirts/v-neck-reversible-jerseys.webp",
            "description": "Custom-sublimated v neck reversible jerseys, made to order for basketball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "basketball-bottoms-jogger-pant",
            "name": "Jogger Pant",
            "quality": "Performance",
            "image": "/basketball uniform/shorts&pents/jogger-pant.webp",
            "description": "Custom-sublimated jogger pant, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-bottoms-team-compression-shorts",
            "name": "Team Compression Shorts",
            "quality": "Performance",
            "image": "/basketball uniform/shorts&pents/team-compression-shorts.webp",
            "description": "Custom-sublimated team compression shorts, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-bottoms-tear-away-pant",
            "name": "Tear Away Pant",
            "quality": "Performance",
            "image": "/basketball uniform/shorts&pents/tear-away-pant.webp",
            "description": "Custom-sublimated tear away pant, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-bottoms-training-shorts",
            "name": "Training Shorts",
            "quality": "Performance",
            "image": "/basketball uniform/shorts&pents/training-shorts.webp",
            "description": "Custom-sublimated training shorts, made to order for basketball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "basketball-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/basketball uniform/hoodie/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/basketball uniform/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for basketball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "basketball-accessories-arm-sleeves",
            "name": "Arm Sleeves",
            "quality": "Team Gear",
            "image": "/basketball uniform/accessries/arm-sleeves.webp",
            "description": "Custom-sublimated arm sleeves, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-accessories-duffle-bag",
            "name": "Duffle Bag",
            "quality": "Team Gear",
            "image": "/basketball uniform/accessries/duffle-bag.webp",
            "description": "Custom-sublimated duffle bag, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-accessories-socks",
            "name": "Socks",
            "quality": "Team Gear",
            "image": "/basketball uniform/accessries/socks.webp",
            "description": "Custom-sublimated socks, made to order for basketball teams in your colors with logo, names & numbers."
          },
          {
            "id": "basketball-accessories-team-backpack",
            "name": "Team Backpack",
            "quality": "Team Gear",
            "image": "/basketball uniform/accessries/team-backpack (1).webp",
            "description": "Custom-sublimated team backpack, made to order for basketball teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 19
  },
  {
    "slug": "baseball",
    "name": "Baseball",
    "icon": "CircleDot",
    "gradient": "from-amber-400/25 to-brand/5",
    "cover": "/SPORTS CETAGORY/BASEBALL.png",
    "tagline": "Custom baseball uniforms, jerseys & team wear",
    "description": "Fully customizable Baseball uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "baseball-uniforms-full-button-baseball-uniforms",
            "name": "Full Button Baseball Uniforms",
            "quality": "Pro Kit",
            "image": "/baseball uniform/products/full-button-baseball-uniforms.webp",
            "description": "Custom-sublimated full button baseball uniforms, made to order for baseball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "baseball-jerseys-batting-practice-jersey",
            "name": "Batting Practice Jersey",
            "quality": "Custom Fit",
            "image": "/baseball uniform/shirts/batting-practice-jersey.webp",
            "description": "Custom-sublimated batting practice jersey, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-jerseys-full-button-baseball-jersey",
            "name": "Full Button Baseball Jersey",
            "quality": "Custom Fit",
            "image": "/baseball uniform/shirts/full-button-baseball-jersey.webp",
            "description": "Custom-sublimated full button baseball jersey, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-jerseys-performance-polo",
            "name": "Performance Polo",
            "quality": "Custom Fit",
            "image": "/baseball uniform/shirts/performance-polo.webp",
            "description": "Custom-sublimated performance polo, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-jerseys-short-sleeve-practice-t-shirt",
            "name": "Short Sleeve Practice T Shirt",
            "quality": "Custom Fit",
            "image": "/baseball uniform/shirts/short-sleeve-practice-t-shirt.webp",
            "description": "Custom-sublimated short sleeve practice t shirt, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-jerseys-sleeveless-baseball-jersey",
            "name": "Sleeveless Baseball Jersey",
            "quality": "Custom Fit",
            "image": "/baseball uniform/shirts/sleeveless-baseball-jersey.webp",
            "description": "Custom-sublimated sleeveless baseball jersey, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-jerseys-two-button-baseball-jersey",
            "name": "Two Button Baseball Jersey",
            "quality": "Custom Fit",
            "image": "/baseball uniform/shirts/two-button-baseball-jersey.webp",
            "description": "Custom-sublimated two button baseball jersey, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-jerseys-v-neck-baseball-jersey",
            "name": "V Neck Baseball Jersey",
            "quality": "Custom Fit",
            "image": "/baseball uniform/shirts/v-neck-baseball-jersey.webp",
            "description": "Custom-sublimated v neck baseball jersey, made to order for baseball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "baseball-bottoms-full-length-baseball-pant",
            "name": "Full Length Baseball Pant",
            "quality": "Performance",
            "image": "/baseball uniform/shorts&pents/full-length-baseball-pant.webp",
            "description": "Custom-sublimated full length baseball pant, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-bottoms-jogger-pant",
            "name": "Jogger Pant",
            "quality": "Performance",
            "image": "/baseball uniform/shorts&pents/jogger-pant.webp",
            "description": "Custom-sublimated jogger pant, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-bottoms-knicker-style-pant",
            "name": "Knicker Style Pant",
            "quality": "Performance",
            "image": "/baseball uniform/shorts&pents/knicker-style-pant.webp",
            "description": "Custom-sublimated knicker style pant, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-bottoms-sliding-shorts",
            "name": "Sliding Shorts",
            "quality": "Performance",
            "image": "/baseball uniform/shorts&pents/sliding-shorts.webp",
            "description": "Custom-sublimated sliding shorts, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-bottoms-training-shorts",
            "name": "Training Shorts",
            "quality": "Performance",
            "image": "/baseball uniform/shorts&pents/training-shorts.webp",
            "description": "Custom-sublimated training shorts, made to order for baseball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "baseball-outerwear-crewneck-sweatshirt",
            "name": "Crewneck Sweatshirt",
            "quality": "Team Wear",
            "image": "/baseball uniform/hoodie/crewneck-sweatshirt.webp",
            "description": "Custom-sublimated crewneck sweatshirt, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/baseball uniform/hoodie/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/baseball uniform/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for baseball teams in your colors with logo, names & numbers."
          },
          {
            "id": "baseball-outerwear-quarter-zipper-batting-pullover",
            "name": "Quarter Zipper Batting Pullover",
            "quality": "Team Wear",
            "image": "/baseball uniform/hoodie/quarter-zipper-batting-pullover.webp",
            "description": "Custom-sublimated quarter zipper batting pullover, made to order for baseball teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 17
  },
  {
    "slug": "soccer",
    "name": "Soccer",
    "icon": "Goal",
    "gradient": "from-yellow-500/25 to-brand/5",
    "cover": "/SPORTS CETAGORY/SOCCER.png",
    "tagline": "Custom soccer uniforms, jerseys & team wear",
    "description": "Fully customizable Soccer uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "soccer-uniforms-collard-soccer-uniform",
            "name": "Collard Soccer Uniform",
            "quality": "Pro Kit",
            "image": "/cosser unifrom/products/collard-soccer-uniform.webp",
            "description": "Custom-sublimated collard soccer uniform, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-uniforms-standard-soccer-uniform",
            "name": "Standard Soccer Uniform",
            "quality": "Pro Kit",
            "image": "/cosser unifrom/products/standard-soccer-uniform.webp",
            "description": "Custom-sublimated standard soccer uniform, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-uniforms-v-neck-soccer-uniform",
            "name": "V Neck Soccer Uniform",
            "quality": "Pro Kit",
            "image": "/cosser unifrom/products/v-neck-soccer-uniform.webp",
            "description": "Custom-sublimated v neck soccer uniform, made to order for soccer teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "soccer-jerseys-custom-v-neck-soccer-jersey",
            "name": "Custom V Neck Soccer Jersey",
            "quality": "Custom Fit",
            "image": "/cosser unifrom/shirts/custom-v-neck-soccer-jersey.webp",
            "description": "Custom-sublimated custom v neck soccer jersey, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-jerseys-goalkeeper-jersey",
            "name": "Goalkeeper Jersey",
            "quality": "Custom Fit",
            "image": "/cosser unifrom/shirts/goalkeeper-jersey.webp",
            "description": "Custom-sublimated goalkeeper jersey, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-jerseys-long-sleeve-training-jersey",
            "name": "Long Sleeve Training Jersey",
            "quality": "Custom Fit",
            "image": "/cosser unifrom/shirts/long-sleeve-training-jersey.webp",
            "description": "Custom-sublimated long sleeve training jersey, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-jerseys-polo-style-soccer-jersey",
            "name": "Polo Style Soccer Jersey",
            "quality": "Custom Fit",
            "image": "/cosser unifrom/shirts/polo-style-soccer-jersey.webp",
            "description": "Custom-sublimated polo style soccer jersey, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-jerseys-short-sleeve-training-shirt",
            "name": "Short Sleeve Training Shirt",
            "quality": "Custom Fit",
            "image": "/cosser unifrom/shirts/short-sleeve-training-shirt.webp",
            "description": "Custom-sublimated short sleeve training shirt, made to order for soccer teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "soccer-bottoms-compression-shorts",
            "name": "Compression Shorts",
            "quality": "Performance",
            "image": "/cosser unifrom/shorts&pents/compression-shorts.webp",
            "description": "Custom-sublimated compression shorts, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-bottoms-custom-soccer-shorts",
            "name": "Custom Soccer Shorts",
            "quality": "Performance",
            "image": "/cosser unifrom/shorts&pents/custom-soccer-shorts.webp",
            "description": "Custom-sublimated custom soccer shorts, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-bottoms-goalkeeper-padded-shorts",
            "name": "Goalkeeper Padded Shorts",
            "quality": "Performance",
            "image": "/cosser unifrom/shorts&pents/goalkeeper-padded-shorts.webp",
            "description": "Custom-sublimated goalkeeper padded shorts, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-bottoms-jogger-pant",
            "name": "Jogger Pant",
            "quality": "Performance",
            "image": "/cosser unifrom/shorts&pents/jogger-pant.webp",
            "description": "Custom-sublimated jogger pant, made to order for soccer teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "soccer-outerwear-crewneck-sweatshirts",
            "name": "Crewneck Sweatshirts",
            "quality": "Team Wear",
            "image": "/cosser unifrom/hoodie/crewneck-sweatshirts.webp",
            "description": "Custom-sublimated crewneck sweatshirts, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/cosser unifrom/hoodie/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/cosser unifrom/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-outerwear-quarter-zip-training-top",
            "name": "Quarter Zip Training Top",
            "quality": "Team Wear",
            "image": "/cosser unifrom/hoodie/quarter-zip-training-top.webp",
            "description": "Custom-sublimated quarter zip training top, made to order for soccer teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "soccer-accessories-backpack",
            "name": "Backpack",
            "quality": "Team Gear",
            "image": "/cosser unifrom/accessries/backpack.webp",
            "description": "Custom-sublimated backpack, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-accessories-duffle-bag",
            "name": "Duffle Bag",
            "quality": "Team Gear",
            "image": "/cosser unifrom/accessries/duffle-bag (1).webp",
            "description": "Custom-sublimated duffle bag, made to order for soccer teams in your colors with logo, names & numbers."
          },
          {
            "id": "soccer-accessories-socks",
            "name": "Socks",
            "quality": "Team Gear",
            "image": "/cosser unifrom/accessries/socks.webp",
            "description": "Custom-sublimated socks, made to order for soccer teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 19
  },
  {
    "slug": "softball",
    "name": "Softball",
    "icon": "CircleDot",
    "gradient": "from-yellow-400/25 to-brand/5",
    "cover": "/SPORTS CETAGORY/SOFTBALL.png",
    "tagline": "Custom softball uniforms, jerseys & team wear",
    "description": "Fully customizable Softball uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "softball-uniforms-racerback-softball-uniforms",
            "name": "Racerback Softball Uniforms",
            "quality": "Pro Kit",
            "image": "/softball uniform/products/racerback-softball-uniforms.webp",
            "description": "Custom-sublimated racerback softball uniforms, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-uniforms-v-neck-softball-uniform",
            "name": "V Neck Softball Uniform",
            "quality": "Pro Kit",
            "image": "/softball uniform/products/v-neck-softball-uniform.webp",
            "description": "Custom-sublimated v neck softball uniform, made to order for softball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "softball-jerseys-2-button-softball-jersey",
            "name": "2 Button Softball Jersey",
            "quality": "Custom Fit",
            "image": "/softball uniform/shirts/2-button-softball-jersey.webp",
            "description": "Custom-sublimated 2 button softball jersey, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-jerseys-full-button-softball-jersey",
            "name": "Full Button Softball Jersey",
            "quality": "Custom Fit",
            "image": "/softball uniform/shirts/full-button-softball-jersey.webp",
            "description": "Custom-sublimated full button softball jersey, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-jerseys-long-sleeve-jersey",
            "name": "Long Sleeve Jersey",
            "quality": "Custom Fit",
            "image": "/softball uniform/shirts/long-sleeve-jersey.webp",
            "description": "Custom-sublimated long sleeve jersey, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-jerseys-performance-tanktop",
            "name": "Performance Tanktop",
            "quality": "Custom Fit",
            "image": "/softball uniform/shirts/performance-tanktop.webp",
            "description": "Custom-sublimated performance tanktop, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-jerseys-round-neck-softball-jersey",
            "name": "Round Neck Softball Jersey",
            "quality": "Custom Fit",
            "image": "/softball uniform/shirts/round-neck-softball-jersey.webp",
            "description": "Custom-sublimated round neck softball jersey, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-jerseys-short-sleeve-t-shirt",
            "name": "Short Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/softball uniform/shirts/short-sleeve-t-shirt.webp",
            "description": "Custom-sublimated short sleeve t shirt, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-jerseys-sleeveless-softball-jersey",
            "name": "Sleeveless Softball Jersey",
            "quality": "Custom Fit",
            "image": "/softball uniform/shirts/sleeveless-softball-jersey.webp",
            "description": "Custom-sublimated sleeveless softball jersey, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-jerseys-v-neck-softball-jersey",
            "name": "V Neck Softball Jersey",
            "quality": "Custom Fit",
            "image": "/softball uniform/shirts/v-neck-softball-jersey.webp",
            "description": "Custom-sublimated v neck softball jersey, made to order for softball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "softball-bottoms-full-length-pant",
            "name": "Full Length Pant",
            "quality": "Performance",
            "image": "/softball uniform/shorts&pent/full-length-pant.webp",
            "description": "Custom-sublimated full length pant, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-bottoms-softball-shorts",
            "name": "Softball Shorts",
            "quality": "Performance",
            "image": "/softball uniform/shorts&pent/softball-shorts.webp",
            "description": "Custom-sublimated softball shorts, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-bottoms-standard-softball-knicker",
            "name": "Standard Softball Knicker",
            "quality": "Performance",
            "image": "/softball uniform/shorts&pent/standard-softball-knicker.webp",
            "description": "Custom-sublimated standard softball knicker, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-bottoms-standard-softball-pant",
            "name": "Standard Softball Pant",
            "quality": "Performance",
            "image": "/softball uniform/shorts&pent/standard-softball-pant.webp",
            "description": "Custom-sublimated standard softball pant, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-bottoms-training-shorts",
            "name": "Training Shorts",
            "quality": "Performance",
            "image": "/softball uniform/shorts&pent/training-shorts.webp",
            "description": "Custom-sublimated training shorts, made to order for softball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "softball-outerwear-crewneck-sweatshirts",
            "name": "Crewneck Sweatshirts",
            "quality": "Team Wear",
            "image": "/softball uniform/hoodie/crewneck-sweatshirts.webp",
            "description": "Custom-sublimated crewneck sweatshirts, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/softball uniform/hoodie/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/softball uniform/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-outerwear-quarter-zipper-pullover",
            "name": "Quarter Zipper Pullover",
            "quality": "Team Wear",
            "image": "/softball uniform/hoodie/quarter-zipper-pullover.webp",
            "description": "Custom-sublimated quarter zipper pullover, made to order for softball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "softball-accessories-backpack",
            "name": "Backpack",
            "quality": "Team Gear",
            "image": "/softball uniform/accessries/backpack (1).webp",
            "description": "Custom-sublimated backpack, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-accessories-cinch-bag",
            "name": "Cinch Bag",
            "quality": "Team Gear",
            "image": "/softball uniform/accessries/cinch-bag.webp",
            "description": "Custom-sublimated cinch bag, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-accessories-socks",
            "name": "Socks",
            "quality": "Team Gear",
            "image": "/softball uniform/accessries/socks.webp",
            "description": "Custom-sublimated socks, made to order for softball teams in your colors with logo, names & numbers."
          },
          {
            "id": "softball-accessories-wheeled-bag",
            "name": "Wheeled Bag",
            "quality": "Team Gear",
            "image": "/softball uniform/accessries/wheeled-bag.webp",
            "description": "Custom-sublimated wheeled bag, made to order for softball teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 23
  },
  {
    "slug": "volleyball",
    "name": "Volleyball",
    "icon": "Disc",
    "gradient": "from-rose-400/20 to-brand/5",
    "cover": "/SPORTS CETAGORY/VOLLEYBALL.png",
    "tagline": "Custom volleyball uniforms, jerseys & team wear",
    "description": "Fully customizable Volleyball uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "volleyball-uniforms-cap-sleeve-volleyball-uniforms",
            "name": "Cap Sleeve Volleyball Uniforms",
            "quality": "Pro Kit",
            "image": "/volleyball uniform/products/cap-sleeve-volleyball-uniforms.webp",
            "description": "Custom-sublimated cap sleeve volleyball uniforms, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-uniforms-volleyball-uniform",
            "name": "Volleyball Uniform",
            "quality": "Pro Kit",
            "image": "/volleyball uniform/products/volleyball-uniform.webp",
            "description": "Custom-sublimated volleyball uniform, made to order for volleyball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "volleyball-jerseys-crewneck-cap-sleeve-jersey",
            "name": "Crewneck Cap Sleeve Jersey",
            "quality": "Custom Fit",
            "image": "/volleyball uniform/shirts/crewneck-cap-sleeve-jersey.webp",
            "description": "Custom-sublimated crewneck cap sleeve jersey, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-jerseys-long-sleeve-t-shirt",
            "name": "Long Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/volleyball uniform/shirts/long-sleeve-t-shirt.webp",
            "description": "Custom-sublimated long sleeve t shirt, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-jerseys-long-sleeve-volleyball-jersey",
            "name": "Long Sleeve Volleyball Jersey",
            "quality": "Custom Fit",
            "image": "/volleyball uniform/shirts/long-sleeve-volleyball-jersey.webp",
            "description": "Custom-sublimated long sleeve volleyball jersey, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-jerseys-racerback-tanktop-jersey",
            "name": "Racerback Tanktop Jersey",
            "quality": "Custom Fit",
            "image": "/volleyball uniform/shirts/racerback-tanktop-jersey.webp",
            "description": "Custom-sublimated racerback tanktop jersey, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-jerseys-short-sleeve-t-shirt",
            "name": "Short Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/volleyball uniform/shirts/short-sleeve-t-shirt.webp",
            "description": "Custom-sublimated short sleeve t shirt, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-jerseys-short-sleeve-volleyball-jersey",
            "name": "Short Sleeve Volleyball Jersey",
            "quality": "Custom Fit",
            "image": "/volleyball uniform/shirts/short-sleeve-volleyball-jersey.webp",
            "description": "Custom-sublimated short sleeve volleyball jersey, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-jerseys-sleeveless-jersey",
            "name": "Sleeveless Jersey",
            "quality": "Custom Fit",
            "image": "/volleyball uniform/shirts/sleeveless-jersey.webp",
            "description": "Custom-sublimated sleeveless jersey, made to order for volleyball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "volleyball-bottoms-athletic-shorts",
            "name": "Athletic Shorts",
            "quality": "Performance",
            "image": "/volleyball uniform/shorts&pent/athletic-shorts.webp",
            "description": "Custom-sublimated athletic shorts, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-bottoms-jogger-pant",
            "name": "Jogger Pant",
            "quality": "Performance",
            "image": "/volleyball uniform/shorts&pent/jogger-pant.webp",
            "description": "Custom-sublimated jogger pant, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-bottoms-poly-spandex-shorts",
            "name": "Poly Spandex Shorts",
            "quality": "Performance",
            "image": "/volleyball uniform/shorts&pent/poly-spandex-shorts.webp",
            "description": "Custom-sublimated poly spandex shorts, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-bottoms-sweat-pant",
            "name": "Sweat Pant",
            "quality": "Performance",
            "image": "/volleyball uniform/shorts&pent/sweat-pant.webp",
            "description": "Custom-sublimated sweat pant, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-bottoms-volleyball-competition-shorts",
            "name": "Volleyball Competition Shorts",
            "quality": "Performance",
            "image": "/volleyball uniform/shorts&pent/volleyball-competition-shorts.webp",
            "description": "Custom-sublimated volleyball competition shorts, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-bottoms-warmup-pant",
            "name": "Warmup Pant",
            "quality": "Performance",
            "image": "/volleyball uniform/shorts&pent/warmup-pant.webp",
            "description": "Custom-sublimated warmup pant, made to order for volleyball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "volleyball-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/volleyball uniform/hoodie/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/volleyball uniform/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-outerwear-quarter-zip-pullover-jacket",
            "name": "Quarter Zip Pullover Jacket",
            "quality": "Team Wear",
            "image": "/volleyball uniform/hoodie/quarter-zip-pullover-jacket.webp",
            "description": "Custom-sublimated quarter zip pullover jacket, made to order for volleyball teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "volleyball-accessories-backpack",
            "name": "Backpack",
            "quality": "Team Gear",
            "image": "/volleyball uniform/accessries/backpack.webp",
            "description": "Custom-sublimated backpack, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-accessories-cinch-bag",
            "name": "Cinch Bag",
            "quality": "Team Gear",
            "image": "/volleyball uniform/accessries/cinch-bag.webp",
            "description": "Custom-sublimated cinch bag, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-accessories-knee-pads",
            "name": "Knee Pads",
            "quality": "Team Gear",
            "image": "/volleyball uniform/accessries/knee-pads.webp",
            "description": "Custom-sublimated knee pads, made to order for volleyball teams in your colors with logo, names & numbers."
          },
          {
            "id": "volleyball-accessories-socks",
            "name": "Socks",
            "quality": "Team Gear",
            "image": "/volleyball uniform/accessries/socks.webp",
            "description": "Custom-sublimated socks, made to order for volleyball teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 22
  },
  {
    "slug": "ice-hockey",
    "name": "Ice Hockey",
    "icon": "Snowflake",
    "gradient": "from-amber-200/20 to-brand/5",
    "cover": "/SPORTS CETAGORY/ICE HOCKEY.png",
    "tagline": "Custom ice hockey uniforms, jerseys & team wear",
    "description": "Fully customizable Ice Hockey uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "ice-hockey-uniforms-away-uniform",
            "name": "Away Uniform",
            "quality": "Pro Kit",
            "image": "/ice hocky uniform/products/away-uniform.webp",
            "description": "Custom-sublimated away uniform, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-uniforms-home-uniform",
            "name": "Home Uniform",
            "quality": "Pro Kit",
            "image": "/ice hocky uniform/products/home-uniform.webp",
            "description": "Custom-sublimated home uniform, made to order for ice hockey teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "ice-hockey-jerseys-compression-base-layer",
            "name": "Compression Base Layer",
            "quality": "Custom Fit",
            "image": "/ice hocky uniform/shirts/compression-base-layer.webp",
            "description": "Custom-sublimated compression base layer, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-jerseys-game-day-jersey-away",
            "name": "Game Day Jersey Away",
            "quality": "Custom Fit",
            "image": "/ice hocky uniform/shirts/game-day-jersey-away.webp",
            "description": "Custom-sublimated game day jersey away, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-jerseys-practice-jersey",
            "name": "Practice Jersey",
            "quality": "Custom Fit",
            "image": "/ice hocky uniform/shirts/practice-jersey.webp",
            "description": "Custom-sublimated practice jersey, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-jerseys-short-sleeve-t-shirt",
            "name": "Short Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/ice hocky uniform/shirts/short-sleeve-t-shirt.webp",
            "description": "Custom-sublimated short sleeve t shirt, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-jerseys-two-tone-hockey-jersey",
            "name": "Two Tone Hockey Jersey",
            "quality": "Custom Fit",
            "image": "/ice hocky uniform/shirts/two-tone-hockey-jersey.webp",
            "description": "Custom-sublimated two tone hockey jersey, made to order for ice hockey teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "ice-hockey-bottoms-hockey-shell",
            "name": "Hockey Shell",
            "quality": "Performance",
            "image": "/ice hocky uniform/shorts&pent/hockey-shell.webp",
            "description": "Custom-sublimated hockey shell, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-bottoms-jogger-pant",
            "name": "Jogger Pant",
            "quality": "Performance",
            "image": "/ice hocky uniform/shorts&pent/jogger-pant.webp",
            "description": "Custom-sublimated jogger pant, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-bottoms-track-pant",
            "name": "Track Pant",
            "quality": "Performance",
            "image": "/ice hocky uniform/shorts&pent/track-pant.webp",
            "description": "Custom-sublimated track pant, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-bottoms-training-shorts",
            "name": "Training Shorts",
            "quality": "Performance",
            "image": "/ice hocky uniform/shorts&pent/training-shorts.webp",
            "description": "Custom-sublimated training shorts, made to order for ice hockey teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "ice-hockey-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/ice hocky uniform/hoodie/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/ice hocky uniform/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for ice hockey teams in your colors with logo, names & numbers."
          },
          {
            "id": "ice-hockey-outerwear-quarter-zipper-pullover",
            "name": "Quarter Zipper Pullover",
            "quality": "Team Wear",
            "image": "/ice hocky uniform/hoodie/quarter-zipper-pullover.webp",
            "description": "Custom-sublimated quarter zipper pullover, made to order for ice hockey teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "ice-hockey-accessories-equipment-bag",
            "name": "Equipment Bag",
            "quality": "Team Gear",
            "image": "/ice hocky uniform/accessries/equipment-bag.webp",
            "description": "Custom-sublimated equipment bag, made to order for ice hockey teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 15
  },
  {
    "slug": "lacrosse",
    "name": "Lacrosse",
    "icon": "Slice",
    "gradient": "from-orange-400/25 to-brand/5",
    "cover": "/SPORTS CETAGORY/LACROSSE.png",
    "tagline": "Custom lacrosse uniforms, jerseys & team wear",
    "description": "Fully customizable Lacrosse uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "lacrosse-uniforms-kilt-skirt",
            "name": "Kilt Skirt",
            "quality": "Pro Kit",
            "image": "/lacrosse uniform/products/kilt-skirt.webp",
            "description": "Custom-sublimated kilt skirt, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-uniforms-women-lacrosse-uniform",
            "name": "Women Lacrosse Uniform",
            "quality": "Pro Kit",
            "image": "/lacrosse uniform/products/women-lacrosse-uniform.webp",
            "description": "Custom-sublimated women lacrosse uniform, made to order for lacrosse teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "lacrosse-jerseys-full-sleeve-lacrosse-jersey",
            "name": "Full Sleeve Lacrosse Jersey",
            "quality": "Custom Fit",
            "image": "/lacrosse uniform/shirts/full-sleeve-lacrosse-jersey.webp",
            "description": "Custom-sublimated full sleeve lacrosse jersey, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-jerseys-lacrosse-sleeveless-jersey",
            "name": "Lacrosse Sleeveless Jersey",
            "quality": "Custom Fit",
            "image": "/lacrosse uniform/shirts/lacrosse-sleeveless-jersey.webp",
            "description": "Custom-sublimated lacrosse sleeveless jersey, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-jerseys-racerback-lacrosse-tanktop",
            "name": "Racerback Lacrosse Tanktop",
            "quality": "Custom Fit",
            "image": "/lacrosse uniform/shirts/racerback-lacrosse-tanktop.webp",
            "description": "Custom-sublimated racerback lacrosse tanktop, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-jerseys-shooting-shirt",
            "name": "Shooting Shirt",
            "quality": "Custom Fit",
            "image": "/lacrosse uniform/shirts/shooting-shirt.webp",
            "description": "Custom-sublimated shooting shirt, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-jerseys-standard-lacrosse-uniform",
            "name": "Standard Lacrosse Uniform",
            "quality": "Custom Fit",
            "image": "/lacrosse uniform/shirts/standard-lacrosse-uniform.webp",
            "description": "Custom-sublimated standard lacrosse uniform, made to order for lacrosse teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "lacrosse-bottoms-compression-shorts",
            "name": "Compression Shorts",
            "quality": "Performance",
            "image": "/lacrosse uniform/shorts&pent/compression-shorts.webp",
            "description": "Custom-sublimated compression shorts, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-bottoms-jogger-pant",
            "name": "Jogger Pant",
            "quality": "Performance",
            "image": "/lacrosse uniform/shorts&pent/jogger-pant.webp",
            "description": "Custom-sublimated jogger pant, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-bottoms-lacrosse-skort",
            "name": "Lacrosse Skort",
            "quality": "Performance",
            "image": "/lacrosse uniform/shorts&pent/lacrosse-skort.webp",
            "description": "Custom-sublimated lacrosse skort, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-bottoms-sweatpant",
            "name": "Sweatpant",
            "quality": "Performance",
            "image": "/lacrosse uniform/shorts&pent/sweatpant.webp",
            "description": "Custom-sublimated sweatpant, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-bottoms-training-shorts",
            "name": "Training Shorts",
            "quality": "Performance",
            "image": "/lacrosse uniform/shorts&pent/training-shorts.webp",
            "description": "Custom-sublimated training shorts, made to order for lacrosse teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "lacrosse-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/lacrosse uniform/hoodie/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/lacrosse uniform/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-outerwear-quarter-zipper-pullover",
            "name": "Quarter Zipper Pullover",
            "quality": "Team Wear",
            "image": "/lacrosse uniform/hoodie/quarter-zipper-pullover.webp",
            "description": "Custom-sublimated quarter zipper pullover, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-outerwear-track-jacket",
            "name": "Track Jacket",
            "quality": "Team Wear",
            "image": "/lacrosse uniform/hoodie/track-jacket.webp",
            "description": "Custom-sublimated track jacket, made to order for lacrosse teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "lacrosse-accessories-bucket-hat",
            "name": "Bucket Hat",
            "quality": "Team Gear",
            "image": "/lacrosse uniform/accessries/bucket-hat.webp",
            "description": "Custom-sublimated bucket hat, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-accessories-cinch-bag",
            "name": "Cinch Bag",
            "quality": "Team Gear",
            "image": "/lacrosse uniform/accessries/cinch-bag.webp",
            "description": "Custom-sublimated cinch bag, made to order for lacrosse teams in your colors with logo, names & numbers."
          },
          {
            "id": "lacrosse-accessories-team-backpack",
            "name": "Team Backpack",
            "quality": "Team Gear",
            "image": "/lacrosse uniform/accessries/team-backpack.webp",
            "description": "Custom-sublimated team backpack, made to order for lacrosse teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 19
  },
  {
    "slug": "rugby",
    "name": "Rugby",
    "icon": "Swords",
    "gradient": "from-red-500/20 to-brand/5",
    "cover": "/SPORTS CETAGORY/RUGBY.png",
    "tagline": "Custom rugby uniforms, jerseys & team wear",
    "description": "Fully customizable Rugby uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "rugby-uniforms-standard-rugby-uniforms",
            "name": "Standard Rugby Uniforms",
            "quality": "Pro Kit",
            "image": "/rugby uniform/products/standard-rugby-uniforms.webp",
            "description": "Custom-sublimated standard rugby uniforms, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-uniforms-v-neck-rugby-uniforms",
            "name": "V Neck Rugby Uniforms",
            "quality": "Pro Kit",
            "image": "/rugby uniform/products/v-neck-rugby-uniforms.webp",
            "description": "Custom-sublimated v neck rugby uniforms, made to order for rugby teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "rugby-jerseys-long-sleeve-tshirt",
            "name": "Long Sleeve Tshirt",
            "quality": "Custom Fit",
            "image": "/rugby uniform/shirts/long-sleeve-tshirt.webp",
            "description": "Custom-sublimated long sleeve tshirt, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-jerseys-polo-shirt",
            "name": "Polo Shirt",
            "quality": "Custom Fit",
            "image": "/rugby uniform/shirts/polo-shirt.webp",
            "description": "Custom-sublimated polo shirt, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-jerseys-round-neck-classic-jersey",
            "name": "Round Neck Classic Jersey",
            "quality": "Custom Fit",
            "image": "/rugby uniform/shirts/round-neck-classic-jersey.webp",
            "description": "Custom-sublimated round neck classic jersey, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-jerseys-short-sleeve-t-shirt",
            "name": "Short Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/rugby uniform/shirts/short-sleeve-t-shirt.webp",
            "description": "Custom-sublimated short sleeve t shirt, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-jerseys-traditional-collard-2-button-jersey",
            "name": "Traditional Collard 2 Button Jersey",
            "quality": "Custom Fit",
            "image": "/rugby uniform/shirts/traditional-collard-2-button-jersey.webp",
            "description": "Custom-sublimated traditional collard 2 button jersey, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-jerseys-v-neck-rugby-jersey",
            "name": "V Neck Rugby Jersey",
            "quality": "Custom Fit",
            "image": "/rugby uniform/shirts/v-neck-rugby-jersey.webp",
            "description": "Custom-sublimated v neck rugby jersey, made to order for rugby teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "rugby-bottoms-classic-rugby-shorts",
            "name": "Classic Rugby Shorts",
            "quality": "Performance",
            "image": "/rugby uniform/shorts&pent/classic-rugby-shorts.webp",
            "description": "Custom-sublimated classic rugby shorts, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-bottoms-compression-shorts",
            "name": "Compression Shorts",
            "quality": "Performance",
            "image": "/rugby uniform/shorts&pent/compression-shorts.webp",
            "description": "Custom-sublimated compression shorts, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-bottoms-jogger-pant",
            "name": "Jogger Pant",
            "quality": "Performance",
            "image": "/rugby uniform/shorts&pent/jogger-pant.webp",
            "description": "Custom-sublimated jogger pant, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-bottoms-track-pant",
            "name": "Track Pant",
            "quality": "Performance",
            "image": "/rugby uniform/shorts&pent/track-pant.webp",
            "description": "Custom-sublimated track pant, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-bottoms-training-shorts",
            "name": "Training Shorts",
            "quality": "Performance",
            "image": "/rugby uniform/shorts&pent/training-shorts.webp",
            "description": "Custom-sublimated training shorts, made to order for rugby teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "rugby-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/rugby uniform/hoodie/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/rugby uniform/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-outerwear-quarter-zipper-pullover",
            "name": "Quarter Zipper Pullover",
            "quality": "Team Wear",
            "image": "/rugby uniform/hoodie/quarter-zipper-pullover (1).webp",
            "description": "Custom-sublimated quarter zipper pullover, made to order for rugby teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "rugby-accessories-cinch-bag",
            "name": "Cinch Bag",
            "quality": "Team Gear",
            "image": "/rugby uniform/accessries/cinch-bag.webp",
            "description": "Custom-sublimated cinch bag, made to order for rugby teams in your colors with logo, names & numbers."
          },
          {
            "id": "rugby-accessories-duffle-bag",
            "name": "Duffle Bag",
            "quality": "Team Gear",
            "image": "/rugby uniform/accessries/duffle-bag.webp",
            "description": "Custom-sublimated duffle bag, made to order for rugby teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 18
  },
  {
    "slug": "flag-football",
    "name": "Flag Football",
    "icon": "Flag",
    "gradient": "from-amber-500/25 to-brand/5",
    "cover": "/SPORTS CETAGORY/FLAG FOOTBALL.png",
    "tagline": "Custom flag football uniforms, jerseys & team wear",
    "description": "Fully customizable Flag Football uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "flag-football-uniforms-flag-football-compression-uniform",
            "name": "Flag Football Compression Uniform",
            "quality": "Pro Kit",
            "image": "/flag football uniform/products/flag-football-compression-uniform.webp",
            "description": "Custom-sublimated flag football compression uniform, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-uniforms-flag-football-uniform",
            "name": "Flag Football Uniform",
            "quality": "Pro Kit",
            "image": "/flag football uniform/products/flag-football-uniform.webp",
            "description": "Custom-sublimated flag football uniform, made to order for flag football teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "flag-football-jerseys-athletic-flag-football-jersey",
            "name": "Athletic Flag Football Jersey",
            "quality": "Custom Fit",
            "image": "/flag football uniform/shirts/athletic-flag-football-jersey.webp",
            "description": "Custom-sublimated athletic flag football jersey, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-jerseys-flag-football-compression-jersey",
            "name": "Flag Football Compression Jersey",
            "quality": "Custom Fit",
            "image": "/flag football uniform/shirts/flag-football-compression-jersey.webp",
            "description": "Custom-sublimated flag football compression jersey, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-jerseys-flag-football-hooded-jersey",
            "name": "Flag Football Hooded Jersey",
            "quality": "Custom Fit",
            "image": "/flag football uniform/shirts/flag-football-hooded-jersey.webp",
            "description": "Custom-sublimated flag football hooded jersey, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-jerseys-flag-football-long-sleeve-jersey",
            "name": "Flag Football Long Sleeve Jersey",
            "quality": "Custom Fit",
            "image": "/flag football uniform/shirts/flag-football-long-sleeve-jersey.webp",
            "description": "Custom-sublimated flag football long sleeve jersey, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-jerseys-long-sleeve-t-shirt",
            "name": "Long Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/flag football uniform/shirts/long-sleeve-t-shirt.webp",
            "description": "Custom-sublimated long sleeve t shirt, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-jerseys-performance-tanktop",
            "name": "Performance Tanktop",
            "quality": "Custom Fit",
            "image": "/flag football uniform/shirts/performance-tanktop.webp",
            "description": "Custom-sublimated performance tanktop, made to order for flag football teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "flag-football-bottoms-athletic-shorts",
            "name": "Athletic Shorts",
            "quality": "Performance",
            "image": "/flag football uniform/shorts&pent/athletic-shorts.webp",
            "description": "Custom-sublimated athletic shorts, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-bottoms-compression-shorts",
            "name": "Compression Shorts",
            "quality": "Performance",
            "image": "/flag football uniform/shorts&pent/compression-shorts.webp",
            "description": "Custom-sublimated compression shorts, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-bottoms-flag-football-athletic-shorts",
            "name": "Flag Football Athletic Shorts",
            "quality": "Performance",
            "image": "/flag football uniform/shorts&pent/flag-football-athletic-shorts.webp",
            "description": "Custom-sublimated flag football athletic shorts, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-bottoms-high-tight-compression-pant",
            "name": "High Tight Compression Pant",
            "quality": "Performance",
            "image": "/flag football uniform/shorts&pent/high-tight-compression-pant.webp",
            "description": "Custom-sublimated high tight compression pant, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-bottoms-jogger-pant",
            "name": "Jogger Pant",
            "quality": "Performance",
            "image": "/flag football uniform/shorts&pent/jogger-pant.webp",
            "description": "Custom-sublimated jogger pant, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-bottoms-track-pant",
            "name": "Track Pant",
            "quality": "Performance",
            "image": "/flag football uniform/shorts&pent/track-pant.webp",
            "description": "Custom-sublimated track pant, made to order for flag football teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "flag-football-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/flag football uniform/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-outerwear-quarter-zip-pullover",
            "name": "Quarter Zip Pullover",
            "quality": "Team Wear",
            "image": "/flag football uniform/hoodie/quarter-zip-pullover.webp",
            "description": "Custom-sublimated quarter zip pullover, made to order for flag football teams in your colors with logo, names & numbers."
          },
          {
            "id": "flag-football-outerwear-zipper-hoodie",
            "name": "Zipper Hoodie",
            "quality": "Team Wear",
            "image": "/flag football uniform/hoodie/zipper-hoodie.webp",
            "description": "Custom-sublimated zipper hoodie, made to order for flag football teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "flag-football-accessories-cinch-bag",
            "name": "Cinch Bag",
            "quality": "Team Gear",
            "image": "/flag football uniform/accessries/cinch-bag.webp",
            "description": "Custom-sublimated cinch bag, made to order for flag football teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 18
  },
  {
    "slug": "esports",
    "name": "Esports",
    "icon": "Gamepad2",
    "gradient": "from-yellow-500/25 to-brand/5",
    "cover": "/SPORTS CETAGORY/ESPORTS.png",
    "tagline": "Custom esports uniforms, jerseys & team wear",
    "description": "Fully customizable Esports uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [
      {
        "id": "uniforms",
        "label": "Full Uniforms",
        "items": [
          {
            "id": "esports-uniforms-esports-uniform",
            "name": "Esports Uniform",
            "quality": "Pro Kit",
            "image": "/esports uniform/products/esports-uniform.webp",
            "description": "Custom-sublimated esports uniform, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-uniforms-full-esports-uniform",
            "name": "Full Esports Uniform",
            "quality": "Pro Kit",
            "image": "/esports uniform/products/full-esports-uniform.webp",
            "description": "Custom-sublimated full esports uniform, made to order for esports teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "jerseys",
        "label": "Jerseys & Shirts",
        "items": [
          {
            "id": "esports-jerseys-esports-jersey",
            "name": "Esports Jersey",
            "quality": "Custom Fit",
            "image": "/esports uniform/shirts/esports-jersey.webp",
            "description": "Custom-sublimated esports jersey, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-jerseys-long-sleeve-esports-jersey",
            "name": "Long Sleeve Esports Jersey",
            "quality": "Custom Fit",
            "image": "/esports uniform/shirts/long-sleeve-esports-jersey.webp",
            "description": "Custom-sublimated long sleeve esports jersey, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-jerseys-polo-shirt",
            "name": "Polo Shirt",
            "quality": "Custom Fit",
            "image": "/esports uniform/shirts/polo-shirt.webp",
            "description": "Custom-sublimated polo shirt, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-jerseys-short-sleeve-t-shirt",
            "name": "Short Sleeve T Shirt",
            "quality": "Custom Fit",
            "image": "/esports uniform/shirts/short-sleeve-t-shirt.webp",
            "description": "Custom-sublimated short sleeve t shirt, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-jerseys-sleeveless-esports-jersey",
            "name": "Sleeveless Esports Jersey",
            "quality": "Custom Fit",
            "image": "/esports uniform/shirts/sleeveless-esports-jersey.webp",
            "description": "Custom-sublimated sleeveless esports jersey, made to order for esports teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "bottoms",
        "label": "Shorts & Pants",
        "items": [
          {
            "id": "esports-bottoms-esports-classic-shorts",
            "name": "Esports Classic Shorts",
            "quality": "Performance",
            "image": "/esports uniform/shorts&pent/esports-classic-shorts.webp",
            "description": "Custom-sublimated esports classic shorts, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-bottoms-esports-pant",
            "name": "Esports Pant",
            "quality": "Performance",
            "image": "/esports uniform/shorts&pent/esports-pant.webp",
            "description": "Custom-sublimated esports pant, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-bottoms-esports-shorts",
            "name": "Esports Shorts",
            "quality": "Performance",
            "image": "/esports uniform/shorts&pent/esports-shorts.webp",
            "description": "Custom-sublimated esports shorts, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-bottoms-jogger-pant",
            "name": "Jogger Pant",
            "quality": "Performance",
            "image": "/esports uniform/shorts&pent/jogger-pant.webp",
            "description": "Custom-sublimated jogger pant, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-bottoms-training-shorts",
            "name": "Training Shorts",
            "quality": "Performance",
            "image": "/esports uniform/shorts&pent/training-shorts.webp",
            "description": "Custom-sublimated training shorts, made to order for esports teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "outerwear",
        "label": "Hoodies & Outerwear",
        "items": [
          {
            "id": "esports-outerwear-full-zip-hoodie",
            "name": "Full Zip Hoodie",
            "quality": "Team Wear",
            "image": "/esports uniform/hoodie/full-zip-hoodie.webp",
            "description": "Custom-sublimated full zip hoodie, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-outerwear-pullover-hoodie",
            "name": "Pullover Hoodie",
            "quality": "Team Wear",
            "image": "/esports uniform/hoodie/pullover-hoodie.webp",
            "description": "Custom-sublimated pullover hoodie, made to order for esports teams in your colors with logo, names & numbers."
          }
        ]
      },
      {
        "id": "accessories",
        "label": "Accessories",
        "items": [
          {
            "id": "esports-accessories-arm-sleeve",
            "name": "Arm Sleeve",
            "quality": "Team Gear",
            "image": "/esports uniform/accessries/arm-sleeve.webp",
            "description": "Custom-sublimated arm sleeve, made to order for esports teams in your colors with logo, names & numbers."
          },
          {
            "id": "esports-accessories-backpack",
            "name": "Backpack",
            "quality": "Team Gear",
            "image": "/esports uniform/accessries/backpack.webp",
            "description": "Custom-sublimated backpack, made to order for esports teams in your colors with logo, names & numbers."
          }
        ]
      }
    ],
    "count": 16
  },
  {
    "slug": "wrestling",
    "name": "Wrestling",
    "icon": "Medal",
    "gradient": "from-orange-500/25 to-brand/5",
    "cover": "/SPORTS CETAGORY/WRESTLING.png",
    "tagline": "Custom wrestling uniforms, jerseys & team wear",
    "description": "Fully customizable Wrestling uniforms and team apparel — sublimated jerseys, shorts, pants, hoodies and accessories. Built to order in your colors, logo, names and numbers, with low minimums and worldwide shipping.",
    "groups": [],
    "count": 0
  }
];

export function getCategory(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function categoryProducts(category: Category): Product[] {
  return category.groups.flatMap((g) => g.items);
}

export const CATEGORY_SLUGS = CATEGORIES.map((c) => c.slug);
